apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167848289
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167848289
    app.kubernetes.io/part-of: test-app-167848289
  name: java-quarkus-167848289
  namespace: qtyadnn8-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-167848289
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-167848289
    spec:
      containers:
      - image: quay.io/hacdev/build_service@sha256:9de0763d63fe9d7abe89bb2d922483ebd83bb0f5577fa5772dafad51ba8f2c1b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
