apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167848289
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167848289
    app.kubernetes.io/part-of: test-app-167848289
  name: java-quarkus-167848289
  namespace: qtyadnn8-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkus-167848289
status:
  loadBalancer: {}
